Readme cleanup
Torantulino/Auto-GPT pull request #1118
Opened 2023-04-13 14:04 UTC by sweetlilmre

### Background
Just a small update to README.md to fix the usage text and clarify the Pinecone integration

### Changes
Only README.md text has been changed

### Documentation
This is a documentation change

### Test Plan
N/A

### PR Quality Checklist
- [X] My pull request is atomic and focuses on a single change.
- [X] I have thoroughly tested my changes with multiple different prompts.
- [X] I have considered potential risks and mitigations for my changes.
- [X] I have documented my changes clearly and comprehensively.
- [X] I have not snuck in any "extra" small tweaks changes

2023-04-13 19:37 UTC, nponeccop requested changes

2023-04-13 19:37 UTC, nponeccop commented on README.md
> +
Delete this line

2023-04-14 08:00 UTC, nponeccop approved these changes

2023-04-14 08:02 UTC, sweetlilmre commented
@richbeales small readme cleanup for you.

2023-04-14 13:46 UTC, p-i- approved these changes

2023-04-14 13:46 UTC, merged