Added and an input for User Advice on each iteration of the loop
Torantulino/Auto-GPT pull request #120
Opened 2023-04-03 23:21 UTC by fjrdomingues

Since I often don't agree with the direction that the bot is going, or because I can save some time and token by giving him advice, I added an input for each iteration where the user can add advice. The autogpt will then take that advice into account for the next iteration.

I took the opportunity to also test my bot for code: https://github.com/fjrdomingues/autopilot

2023-04-04 02:27 UTC, Josedapker commented
Very helpful. Thank you

2023-04-09 10:43 UTC, nponeccop requested changes
Make it more focused. Remove the unrelated changes in gitignore and the .env.template.

2023-04-09 10:43 UTC, nponeccop commented on .env.template
This change is unrelated. Remove from this PR. Keep your PRs atomic to improve the chances of merging.

2023-04-09 10:43 UTC, nponeccop commented on .gitignore
This change is unrelated. Remove from this PR. Keep your PRs atomic to improve the chances of merging.

2023-04-09 10:43 UTC, nponeccop commented on autopilot
Using submodules is a big design decision, making it harder for people to clone. This should be discussed apart.

2023-04-09 10:43 UTC, nponeccop commented on scripts/main.py
> +
An unnecessary whitespace change. Submit it apart.

2023-04-10 08:49 UTC, nponeccop commented
@fjrdomingues Make it more focused and resolve the conflicts

2023-04-10 11:45 UTC, nponeccop approved these changes

2023-04-10 12:47 UTC, nponeccop commented
@fjrdomingues Conflicts again. We are merging minor PRs

2023-04-10 14:24 UTC, nponeccop approved these changes

2023-04-10 22:38 UTC, nponeccop commented
@fjrdomingues There are conflicts again (due to the merged PR batch)

2023-04-11 11:39 UTC, Torantulino commented
Just to clarify, how is this different to the "Human Feedback" that was added in #133?:

![image](https://user-images.githubusercontent.com/22963551/231151043-60f34236-1afa-4454-abfc-1c4de5dd0607.png)

2023-04-11 18:17 UTC, fjrdomingues commented
> Just to clarify, how is this different to the "Human Feedback" that was added in #133?:
> 
> ![image](https://user-images.githubusercontent.com/22963551/231151043-60f34236-1afa-4454-abfc-1c4de5dd0607.png)

Hum. It seems that other PR already solved the same problem! Good catch.
I’ll close this PR.

2023-04-11 18:17 UTC, closed without merging