Add flake8 workflow, clean up whitespace, and remove unwanted prints
Torantulino/Auto-GPT pull request #153
Opened 2023-04-04 07:25 UTC by subramanya1997

- Implement a GitHub Actions workflow to automatically run flake8 linting checks on pull requests. The flake8 workflow configuration can be found in the .github/workflows directory under the file named flake8.yml.
- Clean up extraneous whitespace characters from various parts of the codebase for improved code readability and style consistency.
- Delete unnecessary and debug-related print statements from the code to enhance code clarity and reduce clutter.

This is clean up effort with respect to issue #137

2023-04-04 15:05 UTC, ryanpeach requested changes
Minor complaint but otherwise totally approve and appreciate.

I'd just steal the `requirements-dev.txt`, the workflow, and the setup.cfg (with your modifications) from my PR. Then keep all the code changes from your PR.

2023-04-04 15:05 UTC, ryanpeach commented on .github/workflows/flake8.yml
> +          flake8 --extend-ignore E501,E302,E722,F841 . --count --show-source --statistics
I'd use a setup.cfg like in my PR.

2023-04-04 15:05 UTC, ryanpeach commented on .github/workflows/flake8.yml
> +          pip install flake8
I'd create a `requirements-dev.txt` instead.

2023-04-04 15:05 UTC, ryanpeach commented on .github/workflows/flake8.yml
> +name: Flake8 Lint
Call it "linting" in general so we can add other tools later.

2023-04-04 15:05 UTC, ryanpeach commented on .github/workflows/flake8.yml
> +          python-version: 3.8
We are on 3.11 I believe.

2023-04-04 15:28 UTC, subramanya1997 commented on .github/workflows/flake8.yml
> +          python-version: 3.8
WIll update it.

2023-04-04 15:28 UTC, subramanya1997 commented on .github/workflows/flake8.yml
> +          flake8 --extend-ignore E501,E302,E722,F841 . --count --show-source --statistics
will still your code!

2023-04-04 16:46 UTC, subramanya1997 commented
@ryanpeach made the necessary changes required. Let me know if you think anything needs to be changed.

2023-04-05 18:00 UTC, ryanpeach approved these changes
My CICD issues are resolved.

2023-04-09 11:29 UTC, nponeccop requested changes
Merge the linting-related changes first. For example, create a separate PR with just whitespace correction to match flake8. When it is merged you rebase this one on top and make another small change. And finally when all linting is fixed in the master, you can all the CI to enforce it. Also note that we need to combine this with merging existing PRs so they don't become unmergeable en masse.

@ryanpeach @Torantulino what do you think?

2023-04-10 09:01 UTC, nponeccop commented
@subramanya1997 Now there are conflicts (partially due to a big scope). Split it up and/or resolve the conflicts.

2023-04-10 17:29 UTC, subramanya1997 commented
yeah will do.

2023-04-10 21:02 UTC, ryanpeach commented
> Merge the linting-related changes first. For example, create a separate PR with just whitespace correction to match flake8. When it is merged you rebase this one on top and make another small change. And finally when all linting is fixed in the master, you can all the CI to enforce it. Also note that we need to combine this with merging existing PRs so they don't become unmergeable en masse.
> 
> @ryanpeach @Torantulino what do you think?

I think while ideal, turning a one step processes into 3 step processes, in a repo that has such a slow PR cycle, is a bad idea. It is perfectly fine to merge a flake8 workflow, with flake8 fixes, all at once, even professionally, whereas the alternative will be long and tedious and not improve the quality of the process in any discernable way.

@nponeccop you're doing good work but you aren't a maintainer, and don't know python (by your own admission). Please preface every message/instruction as your opinion, rather than the opinion of the repo.

2023-04-10 22:32 UTC, ryanpeach commented
It's a plan, but here's another plan:

Get all the code quality changes merged into @Torantulino's machine. Test it thoroughly over the course of a day. Become happy with it. Push it to master.

Now, you've broken everyone's PR, but:

1. You only did it once, whereas with my PR's they have been broken at least 4 times over the weekend.
2. Now you have a CICD pipeline to review everyone's changes
3. You did it overnight, and now you can work on features in a clean environment.

2023-04-13 06:34 UTC, richbeales commented
Thanks for this PR, we've now implemented Flake8 linting.  I'll close this PR for now.

2023-04-13 06:34 UTC, closed without merging