Improve Key Validation and Handling in Overwrite Memory and Message Agent Functions
Torantulino/Auto-GPT pull request #208
Opened 2023-04-04 20:56 UTC by slavakurilyak

This pull request introduces improvements to key validation and handling in the `overwrite_memory` and `message_agent` functions within the `scripts/commands.py` file.

Changes include:

-  Adding a new helper function `is_valid_int` to check if a value can be converted to an integer.
-  Updating the `overwrite_memory` function to handle both integer and string keys, and providing more informative error messages.
-  Updating the `message_agent` function to use the `is_valid_int` helper function for key validation and providing an informative error message for invalid keys.

These changes aim to make the code more robust and user-friendly, allowing for better handling of different key types and more informative error messages when invalid keys are encountered.

2023-04-04 22:08 UTC, ryanmac commented
See also https://github.com/Torantulino/Auto-GPT/pull/105

2023-04-05 21:47 UTC, suamai commented on scripts/commands.py
> +        mem.string_key_memory[key] = string
What is the point of saving on this attribute if it is not used anywhere else?

2023-04-06 07:03 UTC, Torantulino commented on scripts/commands.py
> +        mem.string_key_memory[key] = string
``` SYSTEM:  Command memory_ovr returned: Error: module 'memory' has no attribute 'string_key_memory' ```

More importantly, that doesn't even seem to be an existing attribute.

2023-04-06 07:07 UTC, Torantulino requested changes

2023-04-06 07:07 UTC, Torantulino commented on scripts/commands.py
> +        mem.string_key_memory[key] = string
```suggestion
        mem.permanent_memory[key] = string
```

2023-04-06 07:28 UTC, Torantulino requested changes

2023-04-06 07:28 UTC, Torantulino commented on scripts/commands.py
> +        say.speak(agent_response)
```suggestion
        speak.say_text(agent_response, 1)
```

2023-04-06 07:50 UTC, Torantulino approved these changes

2023-04-06 07:50 UTC, merged

2023-04-06 11:08 UTC, Torantulino commented
Fixes #90