Add documentation
Torantulino/Auto-GPT pull request #33
Opened 2023-04-02 17:06 UTC by AndresCdo

This merge request aims to improve the documentation of the functions in the project. The current documentation for the functions is either incomplete or lacks clarity, making it difficult for users to understand the functionalities of the functions.

2023-04-03 08:54 UTC, AndresCdo commented
Hi, @Torantulino I believe it's important to increase documentation in the code and set type of variables of functions parameters.

2023-04-03 10:47 UTC, Torantulino commented
Hi @AndresCdo, thank you for your contribution!
Please fix merge conflicts and I'll get to reviewing this!

2023-04-03 11:53 UTC, AndresCdo commented
> Hi @AndresCdo, thank you for your contribution! Please fix merge conflicts and I'll get to reviewing this!

Conflicts were solved.

2023-04-03 14:03 UTC, rmcsharry approved these changes
LGTM, nice additions.

2023-04-03 14:42 UTC, AndresCdo commented
@Torantulino Everything is ok now.

2023-04-03 20:10 UTC, caretak3r commented
So all you did was clone, and copilot complete for each function? Man what happened to good PRs?

2023-04-03 21:59 UTC, AndresCdo commented
> So all you did was clone, and copilot complete for each function? Man what happened to good PRs?

I did append values in the Dockerfile and I'm working on some implementation of Issues. this is my first time on an Opensource project, thank you for your empathy.

2023-04-04 05:20 UTC, ryanpeach commented
Honestly @AndresCdo I think this is a valuable first step for this codebase. I'd do more than docstrings, but I have no problem if 90% of the comments are AI generated. More comments and code separation are desperately needed. You have my upvote.

2023-04-04 19:40 UTC, AndresCdo commented
@Torantulino @rmcsharry  everything is ok now.

2023-04-09 08:20 UTC, nponeccop requested changes
Since this PR changes many files, make it pinpointed: JUST add documentation. It will simplify the merge. Note that I'm a layperson, it's @Torantulino who approves or disapproves commits.

2023-04-09 08:20 UTC, nponeccop commented on .gitignore
This change is unrelated to the documentation. Remove it and submit as a separate PR

2023-04-09 08:20 UTC, nponeccop commented on Dockerfile
Unrelated as well

2023-04-09 08:20 UTC, nponeccop commented on scripts/ai_config.py
> +
Avoid whitespace changes

2023-04-09 08:20 UTC, nponeccop commented on scripts/ai_config.py
> +
Whitespace

2023-04-09 08:20 UTC, nponeccop commented on scripts/ai_functions.py
> +from json import dumps
It doesn't look like adding documentation to me. Put in a separate PR.

2023-04-09 08:20 UTC, nponeccop commented on scripts/ai_functions.py
> -
Whitespace change again

2023-04-09 08:20 UTC, nponeccop commented on scripts/ai_functions.py
> -
Whitespace

2023-04-09 08:20 UTC, nponeccop commented on scripts/ai_functions.py
> -    args = [code, json.dumps(focus)]
The JSON correction above. Move apart

2023-04-09 08:20 UTC, nponeccop commented on scripts/browse.py
Again whitespace and unrelated changes

2023-04-09 08:20 UTC, nponeccop commented on scripts/call_ai_function.py
The import change is unrelated

2023-04-09 08:20 UTC, nponeccop commented on scripts/chat.py
The cfg movement is unrelated. Import and whitespace changes.

2023-04-09 08:20 UTC, nponeccop commented on scripts/config.py
Whitespace.

2023-04-09 08:20 UTC, nponeccop commented on scripts/main.py
> +
You got the idea at this point I guess

2023-04-09 13:51 UTC, AndresCdo commented
> Since this PR changes many files, make it pinpointed: JUST add documentation. It will simplify the merge. Note that I'm a layperson, it's @Torantulino who approves or disapproves commits.

Thank you so much for your Code Review, corrections were done.

2023-04-09 14:25 UTC, nponeccop requested changes
Remove the introduced trailing whitespace. You may also want to avoid adding and removing empty lines, but it's optional and PR is already pretty focused. Good job!

2023-04-09 14:25 UTC, nponeccop commented on scripts/ai_config.py
> +        full_prompt = f"You are {self.ai_name}, {self.ai_role}\n{prompt_start}\n\nGOALS:\n\n"
Remove the whitespace change here

2023-04-09 14:25 UTC, nponeccop commented on scripts/main.py
> -Continue (y/n): """)
Whitespace again

2023-04-09 14:25 UTC, nponeccop commented on scripts/main.py
> -        "For example: \nIncrease net worth, Grow Twitter Account, Develop and manage multiple businesses autonomously'")
Whitespace

2023-04-09 14:25 UTC, nponeccop commented on scripts/main.py
> -            console_input = input(Fore.MAGENTA + "Input:" + Style.RESET_ALL)
Whitespace

2023-04-09 14:37 UTC, AndresCdo commented
> Remove the introduced trailing whitespace. You may also want to avoid adding and removing empty lines, but it's optional and PR is already pretty focused. Good job!

@Torantulino everything is alright! Let's merge it then.

2023-04-09 14:40 UTC, nponeccop submitted a review, later dismissed

2023-04-09 18:50 UTC, AndresCdo commented
#137

2023-04-10 08:39 UTC, nponeccop submitted a review, later dismissed
It's not ideal, but good enough. Some whitespace changes creeped in, but they are in the same area that this commit changes, I think it's ok especially because #590 takes so long to merge.

2023-04-10 11:06 UTC, Torantulino requested changes

2023-04-10 11:06 UTC, Torantulino commented on scripts/speak.py
> +    """Return the results of a google search"""
```suggestion
    """Speak text using elevenlabs.io's API"""
```

2023-04-10 11:07 UTC, Torantulino approved these changes

2023-04-10 11:07 UTC, merged

2023-04-10 11:13 UTC, nponeccop commented
@AndresCdo Happy end!