typo fix
Torantulino/Auto-GPT pull request #377
Opened 2023-04-07 07:28 UTC by melodysdreamj

### Background

### Changes

### Test Plan

### Change Safety

- [ ] I have added tests to cover my changes
- [ ] I have considered potential risks and mitigations for my changes

2023-04-08 13:21 UTC, richbeales requested changes
Please resubmit without your .idea/ and inspectionProfiles/ directories.

2023-04-08 19:38 UTC, nponeccop requested changes
You need to remove all the extra files you added. If they are beneficial, submit them as separate PRs.

2023-04-08 19:38 UTC, nponeccop commented on .idea/.gitignore
What are all these files? Remove them and keep the PR scope low

2023-04-10 10:24 UTC, nponeccop commented
@melodysdreamj Implement the suggestions and resolve the conflicts

2023-04-10 10:37 UTC, closed without merging