Adds Pre-Commit Hooks, Updates Requirements.txt &  Extends .gitignore
Torantulino/Auto-GPT pull request #388
Opened 2023-04-07 12:00 UTC by helmigsimon

### Background
I noticed that there are some minor issues in the repository:
- Not all dependencies are tagged to a specific version number -> This can lead to code breaking unexpectedly
- There is no automation of code formatting & validity checks -> This leads to inconsistency in the codebase and contributes/maintainers having to deal with unnecessary categories of bugs (i.e. AST violations)
- The `.gitignore` is rather anaemic and doesn't include general Python settings outside of project specific exclusions

### Changes
To address the issues I identified, I have made the folloiwng changes:
- Added pre-commit hooks to the repository, such that certain classes of checks can be executed automatically 
- Tagging packages with the versions downloaded by default as per 2023/04/07
- Introducing dev-requirements.txt for dev packages (only including `pre-commit` for now)
- Deleting ai_settings.yaml as it is unused and in .gitignore

### Test Plan

As these are not functional changes, I have not tested particular cases other than running the scripts/main.py file. 
The script continues to run as expected.

### Change Safety

- [ ] I have added tests to cover my changes
- [ ] I have considered potential risks and mitigations for my changes

2023-04-08 22:50 UTC, nponeccop requested changes
Splitting the PR and reducing the scope of individual changes (e.g. just add the versions without sorting the dependencies) would be nice.

2023-04-08 22:50 UTC, nponeccop commented on ai_settings.yaml
This change shouldn't be in the PR, should it?

2023-04-08 22:50 UTC, nponeccop commented on requirements.txt
> +requests==2.28.2
Requests lines are duplicated

2023-04-08 22:50 UTC, nponeccop commented on .gitignore
The giant .gitignore and pre-commit hooks should be separate PRs.

2023-04-10 10:30 UTC, nponeccop commented
@helmigsimon Now it's additionally out of date. Resolve the conflicts.

2023-04-14 21:12 UTC, richbeales commented
closed as resolved by #1393

2023-04-14 21:12 UTC, closed without merging