logging activity and error in log files in addition to the console
Torantulino/Auto-GPT pull request #434
Opened 2023-04-07 22:33 UTC by fabricehong

…the console

### Background
Related to discussion https://github.com/Torantulino/Auto-GPT/discussions/392

Activity logs will help to analyse agents activity and improve them
Errors logs will help collecting errors in order to debug faster

### Changes

- I moved the main:print_to_console function into a proper file named `logger.py`. I kept the signature, but put it in a Logger class that encapsulate the default python library for logging.
- The logging library accept different logging levels, and provide extensible formatter and handling options.
- The previous behaviour (typing simulation) kept but rewritten in order to fit with the logging library (as a console handler).
- Two new handlers have been added: one for INFO level (activity.log), and one for ERROR level (error.log).
- If the logs folder doesn't exist, it will be created. This folder has been added to the .gitignore

### Test Plan

I tested standard logging, error logging, with and without speak mode. Works great.

### Change Safety

- [ ] I have added tests to cover my changes
- [x] I have considered potential risks and mitigations for my changes

I didn't find necessary to add tests for logging.

2023-04-10 10:38 UTC, nponeccop requested changes

2023-04-10 10:38 UTC, nponeccop commented on .gitignore
Rollback .gitignore as it's unrelated. Submit in a separate PR

2023-04-10 17:03 UTC, fabricehong commented on .gitignore
This PR now creates logs in that directory and shouldn't be commited. That's why I added an extra-line in the .gitignore.

2023-04-10 17:05 UTC, nponeccop approved these changes

2023-04-10 17:55 UTC, fabricehong commented
> The conflicts still remain

alright, solved

2023-04-10 20:30 UTC, nponeccop approved these changes

2023-04-10 22:41 UTC, nponeccop commented
@fabricehong There are conflicts again due to the merging of other PRs

2023-04-11 06:45 UTC, nponeccop commented
Yes, I'm soft of a blind robot just to make the PRs look sane. An advanced linter, if you wish. It's @Torantulino that inspects what the code is actually doing and whether it's beneficial for the project to merge.

2023-04-11 06:49 UTC, nponeccop approved these changes

2023-04-11 12:21 UTC, nponeccop commented
@fabricehong There are conflicts again. I really hope to push it through today.

2023-04-11 13:40 UTC, fabricehong commented
@nponeccop no worries, It was expected due to the number of PR you had to merge.

Ok it's fixed

2023-04-11 14:56 UTC, nponeccop approved these changes

2023-04-12 11:50 UTC, nponeccop commented
@fabricehong Conflicts again. I'm pushing for it to merge before the Batch 3 starts.

2023-04-12 11:56 UTC, fabricehong commented
@nponeccop it should be done in 1 hour. I just realized the debug output with typewriter simulation are not working well when the "Typing..." Spinner is going on. We need to use separate functions for the typing simulation versus simple logging.

2023-04-12 12:46 UTC, fabricehong commented
@nponeccop ok it's done.

Here is what I added:
- I differentiated the type_writer logging from the normal logging by changer the destination logger inside the logging encapsulation
- logging functions are now more explicit (typewriter_log, error, debug, warn).

If you merge other PR before, I'll probably have conflicts again because this PR touches a lot of code.

2023-04-12 12:47 UTC, nponeccop approved these changes

2023-04-12 14:23 UTC, p-i- commented
I've fixed merge conflicts and merged into `staging` branch, which will be later merged into `master`.
Apologies for shoddy workflow and thanks for the PR @fabricehong

2023-04-12 14:23 UTC, closed without merging

2023-04-12 15:07 UTC, fabricehong commented
@p-i- What you cherry-picked on staging won't work because it doesn't include the two latest commits of this afternoon. (see my previous comment).

You need to additionnaly cherry-pick those on staging:
1) 127148d14585e896a674173156578a29788c31b0
2) ce4f729df081ed7cd0d98dae6e88e09b1fb9bdcf

2023-04-12 16:35 UTC, fabricehong commented
@p-i- To facilitate your task, I opened a new PR on staging with the two missing commits, with conflicts solved: https://github.com/Torantulino/Auto-GPT/pull/975

2023-04-12 17:04 UTC, p-i- commented
@fabricehong Sorry, our workflow is in flux right now as we scale up to clear the backlog of PRs. I deleted staging branch, not realizing 975 was against that branch. Could you possibly resubmit it as a PR against master?

2023-04-12 17:30 UTC, fabricehong commented
@p-i- no worries, I totally understand your pain when I see the number or PR :D 

Here it is: https://github.com/Torantulino/Auto-GPT/pull/981

2023-04-12 17:31 UTC, fabricehong commented
I see there is conflicts again. Let me 5 min..