added requirements.in via pip tools
Torantulino/Auto-GPT pull request #49
Opened 2023-04-02 23:08 UTC by astelmach01

Added pip-tools functionality. Instead of adding to requirements.txt, simply add the library to requirements.in and run pip-compile after installing pip-tools

2023-04-04 05:09 UTC, ryanpeach commented
Also related https://github.com/Torantulino/Auto-GPT/issues/137

2023-04-09 10:13 UTC, nponeccop requested changes
Split into independent atomic PRs. While I'm not a maintainer, the current maintainers have a similar requirement in other PRs.

2023-04-09 10:13 UTC, nponeccop commented on Dockerfile
> +FROM python:3.10-slim
Python bump is and using a slim image are separate design decisions. Use 2 separate PRs for this single line as it's easier to approve and merge them.

2023-04-09 10:13 UTC, nponeccop commented on Dockerfile
> +COPY requirements.txt /app/requirements.txt
This change is done elsewhere (in different PRs) already. Search for the PR number(s) and add a comment. Remove from this PR.

2023-04-09 10:13 UTC, nponeccop commented on requirements.in
It's a good idea to generate requirements.txt for a more precice dependency pindown. Explain the advantages and submit only this improvement as a separate PR.

2023-04-09 10:13 UTC, nponeccop commented on scripts/execute_code.py
> -        # You can replace 'python:3.8' with the desired Python image/version
This typo should be a separate PR independent of all the above.

2023-04-14 21:27 UTC, closed without merging