Add Azure OpenAI Service support: specific deployment id by model.
Torantulino/Auto-GPT pull request #580
Opened 2023-04-09 10:13 UTC by suensummit

### Background

Since each deployment is created according to one specific model in Azure OpanAI Service, the deployment id should be specific by model.

### Changes

In `.env.template`, modify `OPENAI_DEPLOYMENT_ID` to `FAST_LLM_MODEL_DEPLOYMENT_ID` and `SMART_LLM_MODEL_DEPLOYMENT_ID`.
Add a function `get_openai_deployment_id` in `llm_utils.py` to specific deployment id by model (fast/smart).
Also updated README.

### Test Plan

### Change Safety

- [ ] I have added tests to cover my changes
- [x] I have considered potential risks and mitigations for my changes

It's more like a modification to fit API requirement, does not affect core functionality.

2023-04-09 11:50 UTC, nponeccop requested changes
Remove the PULL_REQUEST_TEMPLATE changes from the PR.

2023-04-09 11:50 UTC, nponeccop commented on .github/PULL_REQUEST_TEMPLATE.md
This doesn't look right. This is a general file, not specific to this PR

2023-04-09 13:45 UTC, suensummit commented on .github/PULL_REQUEST_TEMPLATE.md
OK thanks

2023-04-09 13:46 UTC, nponeccop approved these changes

2023-04-11 16:21 UTC, nponeccop commented
There are conflicts again.

2023-04-11 17:19 UTC, nponeccop commented on .gitignore
An unrelated change creeped in. Roll it back.

2023-04-11 17:20 UTC, nponeccop commented on scripts/ai_functions.py
Unrelated changes again. They make it harder to review.

2023-04-11 17:21 UTC, nponeccop commented on scripts/main.py
Another unrelated change

2023-04-11 17:21 UTC, nponeccop commented on scripts/speak.py
> -
One more.

2023-04-12 03:19 UTC, suensummit commented
> There are conflicts again.

yeah they are all come from rebase conflicts and it will be quite frustrated if @Torantulino does not intent to merge this PR

2023-04-12 04:00 UTC, closed without merging