Update .env.template
Torantulino/Auto-GPT pull request #592
Opened 2023-04-09 13:24 UTC by Gustavsenay

Replaced all hyphens (-) with underscores (_) in the parameter placeholders that the user needs to set, making it easier to select and paste the correct keys by simply double-clicking them

### Background

### Changes

### Test Plan

### Change Safety

- [ ] I have added tests to cover my changes
- [ ] I have considered potential risks and mitigations for my changes

2023-04-09 13:43 UTC, nponeccop commented
@Torantulino Close as not necessary? The double clicking is entirely editor-specific.

As a counterexample, the clicking on the dashed placeholders works just fine in vim :)

2023-04-09 13:47 UTC, Gustavsenay commented
@nponeccop is just an UX improvement, but I get your point, maybe is better to straight leave those empty? I'm also thinking that an install.bat would be more user friendly to set all the keys, any thoughts about that?

2023-04-09 14:21 UTC, nponeccop commented
@Torantulino has the last saying, so let's wait for him to have time to look

2023-04-10 05:12 UTC, aosan commented
@Gustavsenay love the split of main.py into  role based modules, there are way too many exceptions to handle in a single place. We have multiple back-ends, probably more coming. I've seen the PRs for web front-end. If Pinecode breaks, people can use Redis and vice-versa. 

Empty values in .env is better UX and validation handling. Ideally, modules should check for critical configs in .env, exit with a helpful if desired values are missing. In this way, every future module, integration etc. can do its own validation of configuration with helpful exceptions handling.

@Torantulino this PR is worth considering, would take care of dozens of configuration issues already reported.

2023-04-10 05:33 UTC, nponeccop commented
It shouldn't be called "Update .env.template". @Gustavsenay can you provide a better title?

2023-04-10 05:42 UTC, nponeccop requested changes
Please ensure it only does one thing and doesn't do anything unrelated. The maintainer won't merge PRs silently adding or removing (this happens too!) features.

2023-04-10 05:42 UTC, nponeccop commented on .env.template
> +FAST_LLM_MODEL="gpt_3.5_turbo"
What is this? The dashes are in the model names from the API, so changing them to underscores is counterproductive.

2023-04-10 05:42 UTC, nponeccop commented on .env.template
> +OPENAI_API_KEY=
The previous version was self-documenting, making it easier for people to fill. So I guess the premise of this PR is just wrong. @Torantulino ?

2023-04-10 05:42 UTC, nponeccop commented on .gitignore
Unrelated to other changes. And this is already in #611 . Remove

2023-04-10 05:42 UTC, nponeccop commented on scripts/ai_config.py
Just revert whole file. This is hopefully in #590

2023-04-10 05:42 UTC, nponeccop commented on scripts/main.py
> +    Continue (y/n): """)
Revert the indentation change in an unrelated fragment

2023-04-10 12:51 UTC, closed without merging