replace os with pathlib for ai_config.py
Torantulino/Auto-GPT pull request #647
Opened 2023-04-10 06:52 UTC by Back2Basics

### Background

### Changes

### Documentation

### Test Plan

### PR Quality Checklist
- [ ] My pull request is atomic and focuses on a single change.
- [ ] I have thouroughly tested my changes with multiple different prompts.
- [ ] I have considered potential risks and mitigations for my changes.
- [ ] I have documented my changes clearly and comprehensively.
- [ ] I have not snuck in any "extra" small tweaks changes

2023-04-10 07:06 UTC, nponeccop requested changes
Make the PR more focused:

- My pull request is atomic and focuses on a single change. - NOT TRUE
- I have not snuck in any "extra" small tweaks changes - NOT TRUE

2023-04-10 07:06 UTC, nponeccop commented on scripts/ai_config.py
> -            full_prompt += f"{i+1}. {goal}\n"
Drop unrelated formatting from this PR

2023-04-10 07:06 UTC, nponeccop commented on scripts/ai_config.py
> +
Don't add spaces or move imports around, the PR is not about it.

2023-04-10 07:07 UTC, richbeales commented on scripts/ai_config.py
> +            full_prompt += f"{i + 1}. {goal}\n"
please avoid introducing needless spacing changes unrelated to your PR

2023-04-10 08:33 UTC, nponeccop commented
We will be following the standard. You can submit the changes about improving standard compliance (which one? pep8? isort?) separately from this PR. Some of them are already elsewhere e.g. in #590

2023-04-10 08:34 UTC, nponeccop approved these changes

2023-04-10 22:47 UTC, nponeccop commented
@Back2Basics There are conflicts again due to the merging of other PRs

2023-04-14 16:04 UTC, p-i- commented
Hope this gets updated. Nice change.

2023-04-15 05:23 UTC, closed without merging