[Cleanup] Removed unneeded imports
Torantulino/Auto-GPT pull request #774
Opened 2023-04-11 06:23 UTC by Sma-Das

### Background

Prune unneeded imports

### Changes

Removed stale imports

### Documentation

See changes

### Test Plan

N/A

### PR Quality Checklist
- [ x] My pull request is atomic and focuses on a single change.
- [ ] I have thouroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

2023-04-11 14:05 UTC, nponeccop requested changes

2023-04-11 14:05 UTC, nponeccop commented on scripts/ai_functions.py
> +from typing import List
Remove the trailing space

2023-04-13 20:14 UTC, nponeccop commented
@Sma-Das There are conflicts now

2023-04-13 21:01 UTC, Sma-Das commented
Refactored it to resolve the merge conflict

2023-04-13 21:06 UTC, nponeccop approved these changes

2023-04-13 21:23 UTC, richbeales approved these changes

2023-04-13 21:23 UTC, merged