Remove duplicated unnecessary codes
Torantulino/Auto-GPT pull request #781
Opened 2023-04-11 08:43 UTC by chozzz

### Background
Long support for maintainability, it also helps for others to read the code.

### Changes
- Remove multiple handler for `args.debug`
- Remove Config being instantiated twice.

### Documentation
Not needed

### Test Plan
N/A

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thouroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [ ] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

2023-04-11 14:02 UTC, nponeccop commented
@chozzz There are conflicts now.

2023-04-11 15:02 UTC, nponeccop requested changes

2023-04-11 15:02 UTC, nponeccop commented on scripts/main.py
> -
Whitespace is fixed in separate whitespace-only PRs, so revert this line

2023-04-11 15:11 UTC, chozzz commented
Yeah, its reported here - https://github.com/Torantulino/Auto-GPT/issues/823

2023-04-11 15:15 UTC, chozzz commented on scripts/main.py
> -
Reverted

2023-04-11 15:53 UTC, jaspythonis approved these changes

2023-04-12 05:32 UTC, nponeccop commented
The problem is that the new PR is unmergeable. The maintainer only wants focused PRs fixing a single issue.

2023-04-12 05:47 UTC, chozzz commented
This is a one-liner refactor that doesn't fix anything, and imo it makes more sense for this change to be reviewed with the issues that `master` is facing since they're related. Hence, I raised another PR #888  to fix the issues in `master`.

I'd rather the maintainer to consider the other PR which can unblock `master` from major issues thats breaking it.

2023-04-12 06:40 UTC, nponeccop commented
It does and it has been already reviewed and queued to merge. You broke the pipeline. I suggest reopening.

2023-04-12 08:18 UTC, nponeccop submitted a review, later dismissed
Thanks for the reopening

2023-04-12 18:53 UTC, richbeales approved these changes

2023-04-12 19:18 UTC, nponeccop commented
@chozzz There are conflicts now

2023-04-13 00:02 UTC, chozzz commented
@nponeccop Thanks for letting me know - ive fixed the conflict

2023-04-13 06:15 UTC, nponeccop approved these changes

2023-04-13 06:17 UTC, richbeales approved these changes

2023-04-13 06:17 UTC, merged